export const state = {
  boxes: [],
  deletedBoxIds: {},
  customRooms: null,
  customColorNames: {},
  view: 'list',
  selBox: null,
  selItem: null,
  scanner: null,
  tempBox: null,
  tempItem: null,
  currentUser: 'Nutzer 1',
  scriptUrl: '',
  lastSync: null,
  gClientId: '',
  gToken: null,
  rootFolderId: null,
  isSyncing: false,
  syncDebounceTimer: null,
  toastTimer: null,
  modalPhotoId: null,
  modalIsItem: false,
  modalDriveId: null,
};
